apiVersion: v1
kind: Namespace
metadata:
  name: spring-session-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-session-app
  name: spring-session-app
  namespace: spring-session-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-session-app
  template:
    metadata:
      labels:
        app: spring-session-app
    spec:
      containers:
      - image: crystalline407/spring-session-app:latest
        name: spring-session-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-session-app
  name: spring-session-app
  namespace: spring-session-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-session-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1
  namespace: spring-session-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: spring-session-app
            port:
              number: 8080

