name: push-spring-session-app

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/spring-session-app'
  workflow_dispatch:

env:
  App: 'spring-session-app'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: 'src/spring-session-app'
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.App }}:latest
